### ISSUE TITLE
Error fetching data from the device

### ISSUE THREAD

**Issue by jdammers** [niltrip/powerocean#1]
Many thanks for providing this custom component for the EcoFlow PowerOcean system. Your contribution is greatly appreciated! After installing the component through HACS, 191 sensors have been registered into HomeAssistant. However, the sensor update gets stuck immediately after initialization of the device (sensor will no longer be updated). 
In the logs, I found the following error message: "MY_SERIAL_NUMBER: Error fetching data from the device: 'ecoflow_api' object has no attribute 'fetch_data_km2' " 
When reloading the integration from Homeassistant, sensor values are updated again, but get stuck immediately thereafter.

I am not sure, but the error message maybe created in the function "async_setup_entry() in sensor.py, where either the variable "data" is empty (line 64) due to a device API failure or there is an "IntegrationError" (line 75). Any idea what is causing the problem?

![image](https://github.com/niltrip/powerocean/assets/3457954/28acb826-896a-4265-a59c-0d3ad3b2cf5a)

**Comment by jdammers** [comment]
[BUG FIX]:  it seems that the problem can be solved by changing line 127 from "full_data = await hass.async_add_executor_job(ecoflow.fetch_data_km2)" (old) to (new) "full_data = await hass.async_add_executor_job(ecoflow.**fetch_data**)". 
At least in my case the sensor update is working again :)

**Comment by herbyak** [comment]
Thxs jdammers; that also worked for me. However, under "energy" I don't receive a regular update of data. Any idea?

**Comment by martinarlowski** [comment]
Thxs for your Help. My english is so bad, i try it in german:
Ich hab die Änderung im Script "/homeassistant/custom_components/powerocean/sensor.py" in Zeile 127 durchgeführt und bekommen die Erweiterung ans laufen. Leider werden die Daten nur continuierlich upgedatet, wenn paralell die EcoFlow-APP auf dem Handy läuft. Mache ich etwas falsch?
Vielen Dank für Deinen Support!!! ;)

**Comment by MvH-user** [comment]
![2024-02-19 (7)](https://github.com/niltrip/powerocean/assets/118615915/f2896a71-0dc9-4f9c-b77e-5c7f88ebafaf)
![2024-02-19](https://github.com/niltrip/powerocean/assets/118615915/ac9d09b2-fc93-4814-9c5b-201bc8757709)
Hier mal meine Screenshots von heute , hab immer zwischen durch die App geöffnet um Daten zubekommen. 
ich vermute mal weil das Webportal sich auch nicht Aktualiesiert das  damit zusammen hängt.

**Comment by martinarlowski** [comment]
![Screenshot 2024-02-19 212121](https://github.com/niltrip/powerocean/assets/140853934/6728370f-3061-40cb-ac50-8688e57118d1)

Hier mal ein Screenshot von meiner Anlage. Ich hatte nur zwischendurch mal die App an, und dann werden bei mir sofort die Werte aktualisiert. Sobald die App gestoppt wird, bleiben die Werte konstant. Das Web-Portal von EcoFlow verhält sich leider identisch. Ich meine, das war auch mal anders. Das könnte natürlich auf einen Server-Fehler deuten, oder es hat vielleicht damit zu tun, dass zu viele Clients auf den Server zugreifen und die Daten ziehen wollen. Aber da hab ich leider zu wenig Ahnung von... Danke für Euren Austausch, schön, das ich hier nicht alleine bin ;). Und Danke für Eure Unterstützung!!!

**Comment by herbyak** [comment]
Martin, bei mir sieht es ähnlich aus. Du hast die Antwort zu diesem Problem schon selbst erwähnt. "Das Web Portal von EF verhält sich leider identisch". Da die Daten für HA aus dem Webportal gezogen werden, kann im HA auch nichts anderes angezeigt werden. Der Server von ecoflow steht in China und da kommt es ständig zu Verzügerungen beim Update. Meines Erachtens hat das auch nichts mit der App zu tun. Bei mir erfolgt das Update der Daten  - ca alle 50-60 Sekunden - auch ohne dass ich die App anmachen muss. Hast Du das mal ausprobiert?

**Comment by jdammers** [comment]
@MvH-user @herbyak Die gleichen Ausfälle beobachten wir auch. Der Server in China hängt leider häufig. Wir bekommen aber Werte auch ohne, dass die App an ist.  Eine andere Sache ist, dass der Default zum pull der Sensordaten bei 60s liegt (das hatte man ja bei der Installation in HA eingeben müssen), d.h., im Falle der Server läuft bekommt man dann alle 60s (oder je nach dem was eingestellt war) ein Update das kann dann auch schon mal mit den aktuellen Werten in der App zu unterschieden kommen. Ansonsten denke ich ist das Problem der Server in China, wie @herbyak schon erwähnt hat.

**Comment by martinarlowski** [comment]
Danke für Euer Feedback. Ich werde das mal ein wenig beobachten. Habt Ihr den Wert auf default alle 60 sek gelassen oder verändert? Ich bete, dass Ecoflow hier hoffentlich bald Ihre API für alle öffnet... Bis bald.... :)

**Comment by jdammers** [comment]
@martinarlowski: ja auch 60s.

**Comment by MvH-user** [comment]
Danke Martin  für deine Einschätzung wollen wir mal hoffen das Ecoflow da bald mal was macht.

**Comment by uncledan666** [comment]
Hey all, thanx for developing this great integration!
In general it is working for me. But I get only 10 entities installed and the only power value update is bpPwr. sysLoadPwr, sysGridPwr and mpptPwr are not updated as it has same value as in past, 0.0.
Any idea what the problem can be ?

**Comment by jdammers** [comment]
@uncledan666: I also have 10 entities, plus 198 for diagnostics. Regarding the "no sensor updates" problem - did you follow my instructions above to change line127 in the code of file "sensor.py", i.e., change the line 127 to read: "full_data = await hass.async_add_executor_job(ecoflow.fetch_data)". As I am not the owner of this repo I cannot update the original repo. Instead I made a pull request where this bug is corrected, but until the corrections were not applied into the original code. I'm thinking of providing a new repo, which I will host in the near future, but at the moment I am more in favor of reading out all EcoFlow values using the modbus RTU interface (Cloud-free!!), which is provided at the COM connector, since the Cloud server is often "hanging" (is located in China). If anyone has some experience with Modubus RTU, I would appreciate some guidance.

**Comment by uncledan666** [comment]
@jdammers : Thank you for your reply. The full_data line is changed, yes. Here is all I get:
![grafik](https://github.com/niltrip/powerocean/assets/85431437/40ab6cc8-8b3b-49d9-a5fb-9fc81d644a94)
The offline way by modbus sounds really interesting. Did you allready test if the data is present ? I thought the com interface is only for receiving the power meter values.

**Comment by KaHeMu** [comment]
@jdammers Using the Modbus RTU would really be great - even though it requires an additional cable between the PO and the Smarthome/HA server. (Would be more elegant if the PO was supporting Modbus TCP but AFAIK it doesn't.) Unfortunately I didn't found time to try the Modbus RTU yet but if you could give it a start, I'm more than happy to test it. For a start it would be sufficient to get access to the current data such as current import power, export power, solar power, battery charging/dischargin power. No need for any statistics. I'm not even sure if the PO itself saves the history data or if it is stored on the EF server only.

**Comment by jdammers** [comment]
Thanks @KaHeMu for your comments! I will give it a try soon.

**Comment by niltrip** [comment]
@jdammers thanks for support. I did not realize someone uses my code ;-). For me the integration works to have values for my Energy Dashboard. For daily use i look into the app.
Is there a local Interface? Did you make progress with this?

**Comment by niltrip** [comment]
I have to revise myself. It is actually the case that values are not updated or only in combination with the app. I didn't notice it at the beginning. I probably looked at the app too often ;-). I can't fix that. But I found out that there are currently even more values in the response from the server. Among other things, there are values of the individual strings. It looks like these values are updated more often.

**Comment by jdammers** [comment]
@niltrip I am currently working on this. I am fetching other blocks within the dictionary of 'quota'. Updating seems to work, but I am still in the testing phase. I have made big changes to the current code, but patch-3 is still not finished. I am currently testing locally and want to make sure that all will work, but this will need some more days for testing. Currently I am using less than 30 Sensors, which I found important, but we can discuss.

**Comment by niltrip** [comment]
Sorry i am away for 2 hours. I also work on this. I will checkin today. Have a Look.

**Comment by MvH-user** [comment]
> Da muss ich revidieren. Es ist tatsächlich so, dass Werte nicht oder nur in Kombination mit der App aktualisiert werden. Mir ist das am Anfang nicht aufgefallen. Wahrscheinlich habe ich zu oft in die App geschaut ;-). Beheben kann ich das nicht. Ich habe aber festgestellt, dass aktuell noch mehr Werte in der Antwort vom Server vorkommen. Unter anderem sind da auch Werte der einzelnen Strings dabei. Es sieht so aus, als würden diese Werte häufiger aktualisiert.

Hallo niltrip kannst du sagen welche Werte sich veränderen und welche sensoren das sind ?

**Comment by niltrip** [comment]
Nicht genau. Ich sehe nur, das mpptPwr seltener aktualisiert wird, wenn man nicht in der App ist.
In der response vom Server sind mittlerweile mehr Strukturen drin. Sie haben auch die einzelnen Strings aufgeführt. Diese sind in einem Report der anscheinend zyklisch kommt (JTS1_EMS_HEARTBEAT, heißt ja auch Heartbeat ;-)). Ich wollte noch eine Änderung machen und mehr Daten auslesen (brauche ich selber für das Energiedashboard).

@jdammers ich habe meinen Stand committed (extra branch). Schau doch mal rüber. Mir fehlt noch der "JTS1_BP_STA_REPORT". Dort sind die Daten für die Batterie enthalten (siehe documentation/response_modified.json)

**Comment by jdammers** [comment]
@niltrip bin heute unterwegs. Ich schaue mir das morgen (So) gegen Mittag an. In meinem Code lese ich den Block JTS1_BP_STA_REPORT für alle Batererien aus (in meinem Fall sind es zwei). Das klappt prima. Und die aktualisierung der Sensoren auch. Bis morgen!

**Comment by MvH-user** [comment]
Kurze frage was ist das für ein Cod und wo steckt der und wo kann ich den auslesen

**Comment by jdammers** [comment]
@niltrip ich habe das Auslesen der Batterien in meinem Code als Funktion (jeder dict Block hat eine eigene Funktion). Hier mal für die Batterien:
```
# get sensors from batteries  => JTS1_BP_STA_REPORT
sens_bat = self.__get_battery_sensors(response["data"]["quota"]["JTS1_BP_STA_REPORT"])
dict.update(data, sens_bat)

```
```
def __get_battery_sensors(self, d):
            removed = d.pop('')  # first element is empty
            keys = list(d.keys())
            n_bat = len(keys) - 1  # number of batteries found
            sensors = dict()
            # collect updateTime
            key = 'updateTime'
            value = d[key]
            unique_id = f"{self.sn}_{key}"
            sensors[unique_id] = PowerOceanEndPoint(
                internal_unique_id=unique_id,
                serial=self.sn,
                name=f"{self.sn}_{key}",
                friendly_name=key,
                value=value,
                unit="",
                description="Letzte Aktualisierung"
            )

            # loop over N batteries
            batts = keys[1:]
            ibat = 0
            bat_sens_select = ['bpPwr', 'bpSoc', 'bpSoh', 'bpVol', 'bpAmp', 'bpCycles', 'bpSysState']
            for ibat, bat in enumerate(batts):
                d_bat = json_loads(d[bat])
                for key, value in d_bat.items():
                    if key in bat_sens_select:
                        # default uid, unit and descript
                        unique_id = f"{self.sn}_{bat}_{key}"
                        unit_tmp = ""
                        description_tmp = f"Battery{ibat + 1}_{key}"

                        if key == "bpPwr":
                            unit_tmp = "W"
                            description_tmp = f"Battery{ibat + 1} Leistung"

                        if key == "bpVol":
                            unit_tmp = "V"
                            description_tmp = f"Battery{ibat + 1} Spannung"

                        if key == "bpAmp":
                            unit_tmp = ""
                            description_tmp = f"Battery{ibat + 1} Ampere"

                        if key == "bpCycles":
                            unit_tmp = ""
                            description_tmp = f"Battery{ibat + 1} Ladezyklen"

                        sensors[unique_id] = PowerOceanEndPoint(
                            internal_unique_id=unique_id,
                            serial=self.sn,
                            name=f"{self.sn}_bat{ibat + 1}_{key}",
                            friendly_name=key,
                            value=value,
                            unit=unit_tmp,
                            description=description_tmp
                        )

            # create sensor for number of batteries
            key = 'number_of_batteries'
            unique_id = f"{self.sn}_{key}"
            unit_tmp = ""
            description_tmp = "Anzahl der Batterien"
            sensors[unique_id] = PowerOceanEndPoint(
                internal_unique_id=unique_id,
                serial=self.sn,
                name=f"{self.sn}_{key}",
                friendly_name=key,
                value=n_bat,
                unit=unit_tmp,
                description=description_tmp,
            )

            return sensors
```
Dein Code scheint zu funktionieren. Insgesamt finde ich aber die Anzahl der Sensoren persönlich zu viel. Wenn auch nicht enabled dauert der re-start Vorgang ja länger (da > 500 Sensoren) und belastet das System. Wir brauchen ja eigentlich nur ca. 30 (vllt. 50) Sensoren. Bei mir treffe ich eine Auswahl und die anderen Sensoren werden auch nicht in HA registriert.
Hinweis: In Zeile 77 ist Error undefined. Und json.loads ist deprecated und sollte bald durch json_loads aus homeassistant.util.json ersetzt werden.

**Comment by jdammers** [comment]
@MvH-user mein Code habe ich noch nicht veröffentlicht, da ich mit dem Testen noch nicht fertig war. Ich möchte gerne noch das Sensorupdate beobachten und die Auswahl der wichtigsten Sensoren anpassen. @niltrip hat zwischezeitlich auch schon Änderungen vorgenommen.

**Comment by niltrip** [comment]
@jdammers 
Hi, ich habe mir gestern Deinen Code schon mal angeschaut. 
Willst du selbst releasen oder sollen wir uns zusammentun? Ich würde deine Sachen auch übernehmen. Die Idee "Reports" in einzelnen Funktionen zu bearbeiten ist nicht schlecht. Die Anmeldung hast du auch etwas überarbeitet. Ich bin da ziemlich leidenschaftslos.

Meine Intention war erstmal alle Datenpunkte einlesen. Über eine Auswahl der Parameternamen hole ich mir die "wichtigen" Parameter (get_unit). Das sind dann ca. 60 Datenpunkte und aktuell 274 ohne Einheit disabled. Ein paar doppelte habe ich noch drinnen, weil ich noch mit der Kompatibilität hadere (Neu anlegen ist für mich aber besser, da ich im Energiedashboard gern beide Strings aufführen wollen würde und man den alten Datenpunkt drinlassen muss, sonst ist die Historie weg).
Die Werte würde ich dann nur hoch aus den angebotenen Reports ziehen 

`        
report = "JTS1_EMS_HEARTBEAT"
mpptpvs=["mpptPv1", "mpptPv2"]
unique_id = f"{self.sn}_{report}_mpptHeartBeat_{mpptpv}_{key}"
`

Man kann aber auch eine explizite Liste mit Datenpunkten pflegen... 

Meinst du die Anmeldung am MQTT Broker (ohne ihn zu nutzen) hilft bei der Aktualisierung der Werte?
Bei mir fällt es nicht so auf, ich habe noch ein PowerInsights.

**Comment by jdammers** [comment]
@niltrip Gut, dass du schonmal drauf geschaut hast. Das Repo habe ich nochmal private gemacht, da ich mit dem Testen ja noch nicht fertig war ... musste das ja public machen, da es sonst nicht in HACS eingelsen wird. Ich teile aber gerne alles ... wir können es auch gerne zusammen machen. 
Die Mqtt Zeilen sind  Überbleibsel vom Test  und können gelöscht werden.
Deine Zeilen zu JTS1_EMS_HEARTBEAT sind gut (eventuell auch als Funktion)
Wie war das noch, ich glaube die mpptPwr aus data['quota'] wird selten aktualisiert, wir müssen die aus 'JTS1_ENERGY_STREAM_REPORT' nehmen, richtig?
Soll ich dir mal die neu EcoFlowApi schicken?   Schöner ist es ja wenn es eine PowerOcean Integratin gibt. Wir können alles bei dir im Repo rein pasten. Was meinst du? 
Hier mal die komplette Liste der Sensoren aus meiner Anlage ... was brauchen wir alles?
[PowerOcean_sensor_list_2024-08.pdf](https://github.com/user-attachments/files/16648327/PowerOcean_sensor_list_2024-08.pdf)

**Comment by niltrip** [comment]
@jdammers 
Dann könnte ich ja mal meinen merge committen ;-). Dann können wir darauf ja arbeiten. 
Bis dato habe ich Deine Änderungen bis auf das parsen der Daten übernommen. Da hatte ich auch schon angefangen weiterzumachen. 

Ich teste parallel gerade auf meinen Raspi. Den nächsten Schritt mit devcontainer habe ich leider noch nicht hinbekommen.

Im Moment kann ich leider gar keine Probleme wahrnehmen. Deshalb auch meine blöde Frage zum mqtt. Aber ich hatte das damals auch probiert. Über mqtt bekommt man byte Daten (protobuf als Stichwort) und alle oder andere Frames hat man auch nur bei geöffneter App bekommen. Ich bin hier auch noch mit einem aus dem ecoflow_cloud Projekt in Kontakt, der die protobuf Daten dekodiert (ein Anfang ist in iobroker gemacht mit Anbindung über mqtt an HA). Aber das dauert noch :-(. Deshalb bin ich ja mal wieder an meinem Code dran.

Du kannst es mir gern schicken oder du wartest bis ich committed habe und kannst dann Änderungen machen?

Ich schaue mal in die Liste rein. 
Ich hatte unter documentation eine response.json abgelegt. Ich würde noch eine machen als Vorschlag. Die kann man dann gut vergleichen.

**Comment by jdammers** [comment]
@niltrip Gute Idee!  
Ich warte auf dein Merge. Ich bastel derzeit nur an einer gemeinsamen EcoFlowApi  ... die basiert quasi auf deinen letzten code im branch.
get_uniq() ... habe ich auch übernommen - gute Idee! Brauchst du irgendwas aus JTS1_EMS_CHANGE_REPORT? Ich sehe da nichts nützliches. Ich schaue mir zum Vergleich gerne das json von deinem System an.

**Comment by niltrip** [comment]
@jdammers committed
wie gesagt tobe dich aus, dann können wir reden ;-).

Du hast mich erst wieder darauf gebracht, das Paramter ohne Einheit auch interessant sein können. Ich glaube da muss man auch etwas umbauen. Bsp.: Fehlercodes an den Strings

Aus dem Report nutze ich aktuell bpTotalChgEnergy und bpTotalDsgEnergy im Energiedashboard.
Bsp.: "bpOnlineSum": 2 scheint die Anzahl der Batterien zu sein.
Man lernt erst mit der Anlage, darum auch der Ansatz mit "erstmal alles reinladen" ;-)

Auszug aus parameter_selected.json (lässt sich gut vergleichen gegen response_modified.json)

            "JTS1_EMS_CHANGE_REPORT": { //emsCtrlLedBright setpoint LED
                "mppt1WarningCode": 0,
                "bpOnlineSum": 2,
                "mppt2WarningCode": 0,
                "mppt2FaultCode": 2,
                "mppt1FaultCode": 2,
                "bpTotalChgEnergy": 1138584,
                "bpSoc": 82,
                "emsCtrlLedBright": 10,
                "bpTotalDsgEnergy": 1071090,
            },

**Comment by jdammers** [comment]
OK, und danke für den Merge!! 
bpTotalChgEnergy und bpTotalDsgEnergy  ... stimmt die beiden nutze ich ja auch 
Ich habe so ein Test script (außerhalb von HA) wo ich alle Werte beobachte ... sehr interessant
Vllt macht es Sinn die Kommunikation ausßerhalb der Issues zu machen. Meine Email Adresse ist ja öffentlich (siehe mein Profil)

**Comment by martinarlowski** [comment]
...hört sich klasse an, was ihr beide macht. Ihr seid jetzt schon meine Helden ;)!!! Ich wünschte, ich könnte Euch helfen... Viel Erfolg!!!

**Comment by MvH-user** [comment]
... super was ihr da mach ich freue mich schon auf die Finale Intrigartion . Danke macht weiter so.

**Comment by MvH-user** [comment]
Ach ja das mit der Batterie TotalChgEnergy und bpTotalDsgEnergy im Energiedashboard das läuft bei mir auch schon einge Zeit in 
HA ganz gut ohne Probleme und die Werte stimmen auch über ein mit dem von dem Webportal nur so zu Info an euch.

**Comment by jdammers** [comment]
@all Vielen Dank! Wir bleiben dran und berichten in Kürze
