### ISSUE TITLE
Usage in energy dashboard

### ISSUE THREAD

**Issue by noheton** [niltrip/powerocean#11]
Ich habe die Integration auch für mein PowerOcean System eingerichtet... (auch mal die PublicAPI mit Developer Zugang getestet - aber da ists noch ziemlich dünn) 
Ich bekomme Daten angezeigt - aber scheinbar bekomme ich es nicht hin diese in das Energiedashboard zu übernehmen.
Zum Beispiel kann ich den `mpptPv_pwrTotal` Sensor nicht für die Solarkollektoren auswählen...
Bin da etwas ratlos - vermutlich übersehe ich einen Schritt?
Wäre für Tipps dankbar - oder brauche ich noch einen Template Sensor dafür (wenn ja, wäre ich auch hier für tipps dankbar).

              Hi, der Parameter sysLoadPwr bildet den hausverbrauch ab, ob von Batterie, Netz oder Solar. Berechnen kann man es, aber dafür gibt es auch schöne UIs.

![image](https://github.com/user-attachments/assets/f9adadbe-0bf3-471e-83a9-7abdb3963cf1)

Dort wird rechts auch berechnet, wenn ich keinen Parameter für rechts eintrage. Das wichtigste ist aus meiner Sicht immer der Hauszähler...

_Originally posted by @niltrip in https://github.com/niltrip/powerocean/issues/8#issuecomment-2312970199_

**Comment by blubb-obi** [comment]
todayElectricityGeneration hatte ich auch genommen. Komischerweise sind die Daten um eine Stunde verschoben, also passend für die Winterzeit. Die Daten für die Batterie werden aber korrekt dargestellt.

**Comment by niltrip** [comment]
Das spricht wieder für "Traue keiner Statistik die du nicht selbst gefälscht hast". 
Mir war bis dato nur aufgefallen das ich eine Diskrepanz den Tag über habe (der Energieverbrauch passt nicht immer). Am Ende stimmten die Werte aber. 

Ich glaube der Weg über die eigene Berechnung ist besser.

**Comment by noheton** [comment]
Dankeschön für die Tipps.
