### ISSUE TITLE
Missing data from ecoflow webportal?

### ISSUE THREAD

**Issue by herbyak** [niltrip/powerocean#4]
The data are pulled from the ecoflow webportal, however, I cannot find the data "to home", "to battery", "from battery", "from and to grid" that are shown in the webportal and not in the integration.
Have I missed somehting?

**Comment by SebastianSchaile** [comment]
My interpretation (not 100% sure) is, that:
mpptPwr: From roof to powerocean
sysGridPwr: from and to grid
sysLoadPwr: from Powerocean to house

The values you see on the webportal or app are calculated values from the above and not necessarily correct. In case my home is negative, the values are definitely wrong.

Unfortunately this makes the usage for automatization a bit more difficult.

**Comment by niltrip** [comment]
![grafik](https://github.com/niltrip/powerocean/assets/34488036/170fbce6-4470-44cc-b182-5e40abab3b55)

mpptPwr: From roof to powerocean
sysGridPwr: from and to grid
sysLoadPwr: from Powerocean to house
bpSoc: Batterie Power in %
bpTotalChgEnergy: Power to batterie
bpTotalDsgEnergy: Power from batterie
