### ISSUE TITLE
Abfrageintervall erhöhen und Leistungsdaten der einzelnen Strings

### ISSUE THREAD

**Issue by Filler1971New** [niltrip/powerocean#7]
Hallo,

erst einmal möchte ich mich für den Adapter bedanken. 

Habe hierzu 2 Fragen:
1.) Kann ich den Abfrageintervall nachträglich erhöhen? Derzeit ist es, glaube ich, auf 30Sek eingestellt. Möchte die Werte aber gerne so aktuell haben, wie im WebPortal :)
2.) Im WebPortal kann ich unter Analyse die Leistungsdaten von jedem String (PV1 Leistung, PV2 Leistung) sehen. Kann man diese auch sichtbar machen?

Vielen Dank im Voraus

**Comment by niltrip** [comment]
Hi, nachträglich ändern geht nicht. Einfach das Device löschen und neu anlegen. Der default ist 60s.

Ja, ich habe gesehen, das im json Response mehr Werte drin sind. Ich wollte hier allerdings keine Erweiterungen mehr machen. Ich hoffe in der Ecoflow_cloud Integration erfolgt eine Weiterentwicklung.

**Comment by r32er** [comment]
Ist damit gemeint Integration löschen und neu installieren? Dann kann man eine höhere Abfrage einstellen?
